# Generated by Django 4.2.6 on 2024-03-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0003_remove_grampost_like_postlikes"),
    ]

    operations = [
        migrations.AddField(
            model_name="grampost",
            name="likes",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="siteuser",
            name="profile_pic",
            field=models.ImageField(
                default="static/images/default.jpg", upload_to="static/images/"
            ),
        ),
    ]
