# Generated by Django 4.2.6 on 2024-03-07 21:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0004_grampost_likes_alter_siteuser_profile_pic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postlikes",
            name="like",
        ),
    ]
