# Generated by Django 4.2.6 on 2024-03-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0005_remove_postlikes_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="postlikes",
            name="like",
            field=models.BooleanField(default=False),
        ),
    ]
